version: "3.9"
services:
  web:
    build: . 
    ports:
        - 80:80
    links:
      - db
    depends_on:
      - db

  db:
    image: grugnog/mysql-5.1:latest
    environment:
      MYSQL_DATABASE: wizmall
      MYSQL_USER: wizmall
      MYSQL_PASSWORD: wizmall
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql